name: Hello World Testing Actions.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: 'Check Out Version'

      - name: hello world
        run: echo "Hello World Testing 1"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: pwd
        shell: bash
  
  testing-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: scripts
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Python test file Running
        run: |
          pip3 install requests
          python3 hello.py




    